In [27]:
#PipeLine is used to automate the machine learning process. 
#we can find the best algorithm with better accuracy

import pandas as pd
df=pd.read_csv("C:\\Users\\DELL\\JUPYTER FILES\\MY_PROJECTS\\HR_analytics_with_feats_selection.csv")

In [30]:
x=df.drop(["Unnamed: 0"],axis=1)
x

,region_no,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,avg_training_score,is_promoted
0,region_7,1,35,5.0,8,1,49,0
1,region_22,1,30,5.0,4,0,60,0
2,region_19,1,34,3.0,7,0,50,0
3,region_23,2,39,1.0,10,0,50,0
4,region_26,1,45,3.0,2,0,73,0
...,...,...,...,...,...,...,...,...
54803,region_14,1,48,3.0,17,0,78,0
54804,region_27,1,37,2.0,6,0,56,0
54805,region_1,1,27,5.0,3,1,79,0
54806,region_9,1,29,1.0,2,0,45,0
54807,region_22,1,27,1.0,5,0,49,0

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x["region_no"]=le.fit_transform(x["region_no"])
x

,region_no,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,avg_training_score,is_promoted
0,31,1,35,5.0,8,1,49,0
1,14,1,30,5.0,4,0,60,0
2,10,1,34,3.0,7,0,50,0
3,15,2,39,1.0,10,0,50,0
4,18,1,45,3.0,2,0,73,0
...,...,...,...,...,...,...,...,...
54803,5,1,48,3.0,17,0,78,0
54804,19,1,37,2.0,6,0,56,0
54805,0,1,27,5.0,3,1,79,0
54806,33,1,29,1.0,2,0,45,0
54807,14,1,27,1.0,5,0,49,0

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [64]:
pipe_logistic=Pipeline([("standascaler",StandardScaler()),
              ("Logistic",LogisticRegression())])

pipe_decision=Pipeline([("standascaler",StandardScaler()),
              ("decision",DecisionTreeClassifier())])

pipe_random=Pipeline([("standascaler",StandardScaler()),
              ("randomforest",RandomForestClassifier())])

pipe_svm=Pipeline([("standascaler",StandardScaler()),
              ("svm",SVC())])

pipe_knn=Pipeline([("standascaler",StandardScaler()),
              ("knn",KNeighborsClassifier())])

pipe_naive=Pipeline([("standascaler",StandardScaler()),
              ("naive",GaussianNB())])

pipelines=[pipe_logistic,pipe_decision,pipe_random,pipe_svm,pipe_knn,pipe_naive]

In [70]:
pipedict=dict({0:"Logistic",1:"Decision",2:"randomforest",3:"svm"
              ,4:"knn",5:"naive"})
data=x.iloc[:,:7]
y=x.iloc[:,7]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,y,test_size=0.7)
for i,model in enumerate(pipelines):
    model.fit(x_train,y_train)
    model.predict(x_test)
    print("{} accuracy: {}".format(pipedict[i],model.score(x_train,y_train)))

Logistic accuracy: 0.9169809025665977
Decision accuracy: 0.9991485220776062
randomforest accuracy: 0.9991485220776062
svm accuracy: 0.9173458216761952
knn accuracy: 0.9288407736285124
naive accuracy: 0.9071280866074687

In [76]:
best_accuracy=0
best_classifier=0
best_pipeline=""
for i,model in enumerate(pipelines):
    
    if model.score(x_test,y_test)>best_accuracy:
        best_accuracy=model.score(x_test,y_test)
        best_pipeline=model
        best_classifier=i
print("Best Classifier is {}".format(pipedict[best_classifier]))

Best Classifier is randomforest